"""Re-sync the Issue Tracker artifact's data with GitHub.

The owner reads issues in a private Claude Artifact
(https://claude.ai/artifact/MXvC5hYXLAz4ged3ufUYQy) because GitHub issues often
don't render for them. The page embeds every issue's exact body and every
comment in a `const DATA = [...]` line. This script refreshes that data from the
GitHub API; the page's own layout and script are left alone.

1. Get the current page: Artifact tool, action "read", url above. The result
   names the saved file that holds the full page.
2. python3 tools/sync-tracker.py <that file> [output.html]   (needs GITHUB_TOKEN)
   It strips the wrapper the platform adds around saved pages and updates the
   footer's issue count and sync time.
3. Republish the output with the Artifact tool, passing the same url.

Rules it applies (keep them; CLAUDE.md relies on them):
- Title, body and comments are copied verbatim from GitHub.
- A comment ending in the "Generated by Claude Code" footer is labeled Claude;
  anything else is the owner ("you").
- Closed issues become "done". An open issue marked "done" drops back to
  "progress". Otherwise "open"/"progress" and the per-issue "note" are
  editorial and stay as they are; edit them in the output by hand if needed.
- Issues the tracker doesn't have yet (pull requests are skipped) are added to
  the "Post-launch polish" group, or a group named with --group.
"""
import argparse
import datetime
import json
import os
import pathlib
import re
import urllib.error
import urllib.request

REPO = "Audette-IT/audetteit-site"
FOOTER = "_Generated by [Claude Code](https://claude.ai/code)_"

ap = argparse.ArgumentParser()
ap.add_argument("page")
ap.add_argument("output", nargs="?")
ap.add_argument("--group", default="Post-launch polish")
args = ap.parse_args()


def get(path):
    req = urllib.request.Request(f"https://api.github.com/repos/{REPO}/{path}", headers={
        "Authorization": "Bearer " + os.environ["GITHUB_TOKEN"], "Accept": "application/vnd.github+json"})
    try:
        with urllib.request.urlopen(req, timeout=30) as f:
            return json.load(f)
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return None
        raise


def comments(n):
    # The issue's own "comments" count reads 0 for this token, so always fetch the list.
    return [{"by": "claude" if (c["body"] or "").rstrip().endswith(FOOTER) else "you",
             "at": c["created_at"], "body": c["body"] or ""}
            for c in get(f"issues/{n}/comments?per_page=100") or []]


page = pathlib.Path(args.page)
html = page.read_text()
# A file saved by the Artifact tool's "read" includes the wrapper the platform
# adds at publish time (<!doctype html>...<body>). Strip it, or a republish
# would wrap the page twice.
if html.lstrip().lower().startswith("<!doctype"):
    html = html[html.index("<body>") + len("<body>"):].lstrip("\n")
    html = re.sub(r"\s*</body>\s*</html>\s*$", "\n", html)
start = html.index("const DATA = ")
end = html.index(";\n", start)
data = json.loads(html[start + len("const DATA = "):end])

changes = []
known = set()
for group in data:
    # Groups from another repo (e.g. "Help desk", repo Audette-IT/audetteit-help)
    # carry a "repo" key. Their numbers overlap this repo's, so leave them for
    # that repo's session to sync.
    if group.get("repo", REPO) != REPO:
        continue
    for item in group["items"]:
        n = item["n"]
        known.add(n)
        issue = get(f"issues/{n}")
        old = item["s"]
        item["t"], item["body"], item["c"] = issue["title"], issue["body"] or "", comments(n)
        if issue["state"] == "closed":
            item["s"] = "done"
        elif item["s"] == "done":
            item["s"] = "progress"
        if item["s"] != old:
            changes.append(f"#{n}: {old} -> {item['s']}")

# Look for issues the tracker doesn't have yet, past the highest known number.
misses, n = 0, max(known)
while misses < 15:
    n += 1
    issue = get(f"issues/{n}")
    if issue is None:
        misses += 1
        continue
    misses = 0
    if "pull_request" in issue or n in known:
        continue
    group = next((g for g in data if g["cat"] == args.group), None)
    if group is None:
        group = {"cat": args.group, "items": []}
        data.append(group)
    group["items"].append({"n": n, "t": issue["title"], "s": "done" if issue["state"] == "closed" else "open",
                           "body": issue["body"] or "", "c": comments(n), "note": ""})
    changes.append(f"#{n}: added to '{args.group}'")

html = html[:start] + "const DATA = " + json.dumps(data, ensure_ascii=False).replace("</", "<\\/") + html[end:]

counts = {"open": 0, "progress": 0, "done": 0}
for group in data:
    for item in group["items"]:
        counts[item["s"]] += 1
total = sum(counts.values())
# The page footer says how many issues it holds and when it was synced.
stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
html = re.sub(r"\d+ issues &middot; synced from GitHub [^<]*", f"{total} issues &middot; synced from GitHub {stamp}", html)

out = pathlib.Path(args.output) if args.output else page
out.write_text(html)
print("\n".join(changes) or "No status changes.")
print(f"{total} issues: {counts['done']} done / {counts['progress']} in progress / {counts['open']} open -> {out}")
